import {
  boolean,
  integer,
  pgTable,
  text,
  timestamp,
  varchar,
} from "drizzle-orm/pg-core";

export const usersTable = pgTable("users", {
  // Primary key
  id: integer().primaryKey().generatedAlwaysAsIdentity(),

  // Basic info (from CSV)
  name: varchar({ length: 255 }).notNull(),
  email: varchar({ length: 255 }).notNull().unique(),
  slackId: varchar({ length: 100 }), // Slack username
  profilePic: text(), // Profile picture URL

  // Social links (from CSV)
  twitter: varchar({ length: 100 }), // X/Twitter handle (without @)
  linkedin: varchar({ length: 255 }), // LinkedIn profile identifier
  site: text(), // Personal website URL

  // X/Twitter data (populated from X API)
  xUserId: varchar({ length: 50 }), // X user ID (string)
  xUsername: varchar({ length: 100 }), // X username
  xDescription: text(), // X bio/description
  xLocation: varchar({ length: 255 }), // Location from X profile
  xUrl: text(), // URL from X profile
  xVerified: boolean().default(false), // Verified status
  xVerifiedType: varchar({ length: 50 }), // Type of verification
  xFollowersCount: integer().default(0), // Public followers count
  xFollowingCount: integer().default(0), // Public following count
  xListedCount: integer().default(0), // Public listed count
  xTweetCount: integer().default(0), // Public tweet count
  xCreatedAt: timestamp(), // Account creation date from X

  // Derived fields (from Grok enrichment)
  derivedRole: varchar({ length: 100 }), // e.g., "founder", "engineer", "researcher"
  derivedTopics: text().array(), // Array of topics/interests
  derivedSummary: text(), // Short summary generated by Grok

  // Classification
  isBaseUser: boolean().default(false).notNull(), // identifies original seed users

  // Timestamps
  createdAt: timestamp().defaultNow().notNull(),
  updatedAt: timestamp().defaultNow().notNull(),
  lastRefreshedAt: timestamp(), // Last time data was refreshed from X API
});
